import { Suspense } from 'react';
import { ArrowDown, HeartHandshake, BriefcaseBusiness, BookOpen } from 'lucide-react';
import ContactForm from '@/components/ContactForm';
import ContactSwitch from '@/components/ContactSwitch';
export const metadata = { title: 'Contato', description: 'Entre em contato com o Espaço Resilience Psicologia. Formulários específicos para atendimento clínico, empresas, cursos e outras solicitações.' };
export default function Contact() { return <>
  <section className="page-hero page-hero--minimal contact-hero"><div className="shell"><span className="eyebrow">ESTAMOS AQUI PARA ACOLHER</span><h1>O primeiro passo é <em>entrar em contato.</em></h1><p>Escolha o tipo de solicitação e envie sua mensagem para que ela seja encaminhada à área adequada.</p><a className="text-link" href="#formulario">Preencher formulário <ArrowDown size={18}/></a></div></section>
  <section className="section contact-section" id="formulario"><div className="shell contact-layout"><aside className="contact-aside"><span className="eyebrow">UMA CONVERSA DE CADA VEZ</span><h2>Como podemos <em>ajudar?</em></h2><p>Cada solicitação recebe o encaminhamento apropriado, seja para atendimento clínico, ações em empresas ou informações sobre atividades.</p><div className="contact-aside__item"><HeartHandshake size={22}/><span><strong>Atendimento clínico</strong><small>Informações sobre psicoterapia e orientação profissional.</small></span></div><div className="contact-aside__item"><BriefcaseBusiness size={22}/><span><strong>Empresas</strong><small>Propostas para organizações e equipes.</small></span></div><div className="contact-aside__item"><BookOpen size={22}/><span><strong>Cursos e eventos</strong><small>Informações sobre atividades e publicações.</small></span></div><div className="contact-aside__notice"><strong>Importante</strong><p>Para sua privacidade, não compartilhe informações de saúde ou situações clínicas detalhadas neste formulário. Essas questões podem ser conversadas no contexto adequado de atendimento.</p></div></aside><div className="contact-form__panel"><Suspense fallback={<ContactForm/>}><ContactSwitch/></Suspense></div></div></section>
</>; }
