import Link from 'next/link';
import { ArrowUpRight, BookOpen, CalendarDays, Users } from 'lucide-react';
import { coursesAndBooks } from '@/data/editorial';
export const metadata = { title: 'Cursos e livros', description: 'Cursos, grupos, workshops, eventos e publicações do Espaço Resilience Psicologia.' };
export default function CoursesPage() { return <>
  <section className="page-hero page-hero--minimal"><div className="shell"><span className="eyebrow">APRENDIZAGEM E PARTILHA</span><h1>Encontros que ampliam <em>possibilidades.</em></h1><p>Cursos, grupos, workshops, eventos e publicações para aprofundar reflexões e compartilhar conhecimento.</p></div></section>
  <section className="section"><div className="shell"><div className="section-topline"><div><span className="eyebrow">NOSSA AGENDA</span><h2>Próximas experiências e <em>publicações.</em></h2></div><p>Confira os projetos divulgados pelo espaço e solicite informações específicas pelo formulário de cursos.</p></div>
  {coursesAndBooks.length ? <div className="course-grid">{coursesAndBooks.map(item=><article className="course-card" key={item.slug||item.title}><div className="course-card__icon"><BookOpen size={27}/></div><span className="eyebrow">{item.category||'CURSO E PUBLICAÇÃO'}</span><h3>{item.title}</h3><p>{item.description}</p><div className="course-card__meta">{item.date && <span><CalendarDays size={16}/>{item.date}</span>}{item.spots && <span><Users size={16}/>{item.spots}</span>}{item.price && <span>Investimento: {item.price}</span>}</div><a className="button button--outline" target={item.url ? '_blank' : undefined} rel={item.url ? 'noopener noreferrer' : undefined} href={item.url || '/contato?tipo=cursos'}>{item.buttonLabel||'Saiba mais'}<ArrowUpRight size={17}/></a></article>)}</div> : <div className="courses-empty"><div className="courses-empty__symbol"><BookOpen size={49} strokeWidth={1.1}/></div><span className="eyebrow">EM BREVE</span><h3>Novidades estão a caminho.</h3><p>Estamos organizando informações sobre cursos, grupos, workshops, eventos e publicações. Você já pode falar conosco e demonstrar interesse.</p><Link href="/contato?tipo=cursos" className="button button--green">Tenho interesse <ArrowUpRight size={17}/></Link></div>}</div></section>
  <section className="section section--sand course-footer"><div className="shell"><span className="eyebrow">TEM ALGUMA DÚVIDA?</span><h2>Fale diretamente com o <em>setor de cursos.</em></h2><p>Centralizamos solicitações sobre cursos e eventos em um formulário próprio para facilitar seu atendimento.</p><Link className="button button--outline" href="/contato?tipo=cursos">Solicitar informações <ArrowUpRight size={18}/></Link></div></section>
</>; }
