import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, GraduationCap, HandHeart } from 'lucide-react';
export const metadata = { title: 'Profissionais', description: 'Conheça a trajetória e as abordagens de atendimento da equipe do Espaço Resilience Psicologia.' };
export default function Professionals() {
  return <>
    <section className="page-hero page-hero--minimal"><div className="shell"><span className="eyebrow">PESSOAS QUE CUIDAM DE PESSOAS</span><h1>Uma escuta que considera <em>a sua história.</em></h1><p>Conheça as trajetórias de quem constrói o trabalho do Espaço Resilience, unindo experiência, atualização profissional e acolhimento.</p></div></section>
    <section className="section"><div className="shell profile-feature"><div className="profile-feature__media"><Image src="/images/retrato-equipe-01.webp" fill sizes="(max-width: 850px) 90vw, 42vw" className="cover cover--portrait" alt="Retrato de integrante da equipe do Espaço Resilience"/></div><div className="profile-feature__content"><span className="eyebrow">TRAJETÓRIA PROFISSIONAL</span><h2>Andréia Mansk <em>Boone Salles</em></h2><p className="profile-feature__crp">Psicóloga · CRP 16/1085</p><p>Psicóloga há 24 anos e doutora em Psicologia pela UFES, com formação internacional e atuação clínica junto a crianças, adolescentes e adultos.</p><div className="profile-feature__highlights"><span><GraduationCap size={20}/> Doutorado em Psicologia</span><span><HandHeart size={20}/> Psicoterapia EMDR e abordagens integrativas</span></div><div className="profile-feature__approaches"><strong>Abordagens</strong><div><span>EMDR</span><span>Terapia do Esquema</span><span>Terapia Focada na Compaixão</span><span>Ludoterapia</span><span>Sandplay</span></div></div><Link href="/profissionais/andreia" className="button button--green">Conheça a trajetória completa <ArrowUpRight size={18}/></Link></div></div><p className="shell profile-photo-note">A associação entre os retratos recebidos e os nomes dos profissionais deverá ser confirmada antes da publicação definitiva.</p></section>
    <section className="section section--sand team-note"><div className="shell team-note__grid"><div><span className="eyebrow">NOSSA EQUIPE</span><h2>Uma equipe que valoriza <em>o encontro humano.</em></h2><p>O espaço conta com profissionais apresentados em nossos materiais. As informações sobre outros perfis serão publicadas aqui após validação dos respectivos dados biográficos e registros profissionais.</p><Link href="/contato" className="text-link">Fale com nossa equipe <ArrowUpRight size={18}/></Link></div><div className="team-note__image"><Image src="/images/retrato-equipe-02.webp" fill sizes="(max-width: 850px) 90vw, 35vw" alt="Retrato profissional de integrante da equipe" className="cover cover--portrait" /></div></div></section>
  </>;
}
