import Image from 'next/image';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight, ExternalLink } from 'lucide-react';
export const metadata = { title: 'Andréia Mansk Boone Salles', description: 'Conheça a formação, as abordagens e a trajetória clínica e acadêmica da psicóloga Andréia Mansk Boone Salles, CRP 16/1085.' };
export default function Andreia() {
  return <>
    <section className="page-hero page-hero--bio"><div className="shell"><Link href="/profissionais" className="back-link"><ArrowLeft size={18}/> Voltar aos profissionais</Link><div className="bio-hero__grid"><div><span className="eyebrow">CONHEÇA A TRAJETÓRIA</span><h1>Andréia Mansk <em>Boone Salles.</em></h1><p className="bio-hero__role">Psicóloga · CRP 16/1085</p><p>Atuação clínica com crianças, adolescentes e adultos, com atenção especial a traumas psicológicos, autorregulação emocional, resiliência e desenvolvimento humano.</p><Link href="/contato?tipo=clinico" className="button button--green">Solicitar atendimento <ArrowUpRight size={18}/></Link></div><div className="bio-hero__photo"><Image src="/images/retrato-equipe-01.webp" fill sizes="(max-width: 850px) 90vw, 35vw" alt="Retrato de integrante da equipe do Espaço Resilience, associação de nome a confirmar" className="cover cover--portrait" priority/></div></div></div></section>
    <section className="section"><div className="shell biography"><div className="biography__sidebar"><span className="eyebrow">FORMAÇÃO E ABORDAGENS</span><h2>Ciência e cuidado <em>em diálogo.</em></h2></div><div className="biography__body"><h3>Formação acadêmica</h3><p>Sou psicóloga (CRP 16/1085), formada há 24 anos. Doutora em Psicologia pela Universidade Federal do Espírito Santo (UFES), possuo mestrado pela Canterbury Christ Church University, no Reino Unido, e formação de pós-graduação em Ludoterapia pela The Academy of Play and Child Psychotherapy, também na Inglaterra.</p><h3>Atuação clínica</h3><p>Sou psicoterapeuta certificada em EMDR pela Associação Ibero-Americana de Psicotrauma (AIBAPT), da qual sou membro pleno. Minha atuação clínica inclui o atendimento de crianças, adolescentes e adultos, com foco especialmente em traumas psicológicos, autorregulação emocional, resiliência e desenvolvimento humano.</p><p>Na prática clínica, trabalho principalmente com Psicoterapia EMDR, Terapia do Esquema e Terapia Focada na Compaixão, integrando, quando indicado, recursos da Ludoterapia e do Sandplay. A escolha das estratégias terapêuticas considera a história, as necessidades e o contexto de cada pessoa.</p><h3>Trajetória profissional e publicações</h3><p>Minha trajetória abrange a Psicologia Clínica com crianças, adolescentes e adultos, a Ludoterapia, a Psicologia Hospitalar e a docência no Ensino Superior e em cursos de Pós-Graduação. Sou autora de artigos científicos publicados em revistas nacionais e internacionais.</p><div className="biography__links"><span>CRP 16/1085</span><a href="http://lattes.cnpq.br/7291176144176372" target="_blank" rel="noopener noreferrer">Consultar Currículo Lattes <ExternalLink size={17}/></a></div></div></div></section>
  </>;
}
